services:
  redis:
    image: redis:7-alpine
    container_name: smartpetpath-redis
    command: ["redis-server", "--save", "", "--appendonly", "no", "--requirepass", "myredispass"]
    ports:
      - "6379:6379"
